<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Home Services - Home Page</title>

<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<?php include('meta_tags.php'); ?>
</head>
<body>
	<?php include('user_header.php');
include('../admin/dbconnect.php');
	 ?>
	<div class="main-banner banner text-center">
	  <div class="container"> 
	  
	  </div>
	</div>
		<!-- content-starts-here -->
 		<div class="content">
		 
			<hr>
			
			<div class="categories">
				<div class="container">

				 <!---------  Start //--->

<?php
$requestid=$_REQUEST['customer_id'];
   $customer_name=$_REQUEST['custname'];
  
  $email_id=$_REQUEST['custemail'];
  $contact_no=$_REQUEST['custphone'];
  $rate=$_REQUEST['rate'];
  
  
include 'razorpay-php/Razorpay.php';
 //$apiKey = "rzp_test_YxfkUbFXwfG4Vc";
 use Razorpay\Api\Api;


$keyId = 'rzp_test_fDmVzWIk43LrqG';
$secretKey = '2vqsxsdMHHdMpVrmvQoP5x5h';
$api = new Api($keyId, $secretKey);


$amount=$rate;

$paise=$amount*100;

$order= $api->order->create(array(
'receipt'=>rand(1000,9999).'ORD',
'amount'=>$paise,
'payment_capture'=>1,
'currency'=>'INR',)
);
?>
<form name="form1" id="formID" method="post" action="pay_insert.php">
<input type="hidden" name="requestid" value="<?php echo $requestid; ?>">

  <table width="491" height="148" border="0" align="center">
    <tr>
      <td width="185" height="51">Customer Name </td>
      <td width="296"><input name="customer_id" id="customer_id" value="<?php echo $customer_name;?>" readonly="" class="form-control validate[required]">
      <tr>
        <td height="54">Payment Type </td>
        <td><input name="Payment_type" readonly="" class="form-control" type="text" id="Payment_type" value="Online">      
      <tr>
        <td height="32">Price</td>
        <td><input name="price" type="text" readonly="" value="<?php echo $_REQUEST['rate'];?>" id="price" class="form-control validate[required[custom,onlyNumber]]"></td>
      </tr>
      <tr>
        <td colspan="2"></td>
      </tr>
  </table>
  <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard ? Settings ? API Keys
    data-amount="<?php echo $order->amount; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ?299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="HOME SERVICES"
    data-description=""
    data-image="https://www.dealsshutter.com/blog/wp-content/uploads/2020/03/Home-Services-Image-30-march-2020.png"
    data-prefill.name="<?php echo $customer_name;  ?>"
	data-prefill.contact="<?php echo $contact_no;  ?>"
    data-prefill.email="<?php echo $email_id ?>"
    data-theme.color="#283179"
>
  </script>
</form>
</tbody>
                              </table>
					
					<div class="clearfix"></div>
				</div>
			</div>
			
			
		</div>
		<!--footer section start-->		
		<?php include('footer.php'); ?>
        <!--footer section end-->
</body>
</html>